### PR TITLE
fixed slide name = 0 issue

### LINKED ISSUE #1: Passing 0 as slide name fails
If you pass 0 to the name of the slide (like when using an array index as slide names), active slide can't be set.

### PR DESCRIPTION
**Pull request by donaldwasserman**
Fixes #1

### CODE REVIEW

**Comment by donaldwasserman** [comment]
@crhayes sorry about all the code reformatting, I was trying out a new editor and it has some different settings than I'm used to. I'll clean that up.

**Comment by crhayes** [comment]
@donaldwasserman I noticed a commit `fix issue with object teardowns`. I have been having this issue as well. I've been trying to write a failing test for this case without success. Do you have specific steps that could replicate this issue?

**Comment by crhayes** [comment]
@donaldwasserman It seems like it's only happening on Ember 3.2. I pushed up a PR that should fix it. I'm going to be merging in several fixes shortly as well as an upgrade to Ember 3.2. I'll tag a new release when it's all done!

**Comment by donaldwasserman** [comment]
Yeah - I encountered the error when we upgraded to 3.2. There's some debate if there's a different way ember is handling `this.send()` i saw in a different addon. 

Thanks for checking in on this.

**Comment by crhayes** [comment]
I appreciate the PR. However, I'm closing in favour of https://github.com/crhayes/ember-slides/pull/5.

**Comment by donaldwasserman** [comment]
@crhayes did you cut a new release on npm? 

Thanks for taking care of this.

**Comment by crhayes** [comment]
@donaldwasserman Yessir. Released `0.3` on npm.

**Pull request closed without merging**
